version: '3'
services:
  mongodb:
    image: mongo:4
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=S4nt0s
      - MONGO_INITDB_ROOT_PASSWORD=EGdQnKnTSe8VCv63

  redis:
    image: redis:5.0.3
    container_name: redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

  app:
    container_name: time-tracker
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    env_file: 
      - ./app.env
    restart: always
    build: ./app
    ports:
      - "5000:5000"
      - "9229:9229"
    links:
      - mongodb
      - redis
    depends_on: 
      - mongodb
      - redis
    command: sh -c "npm start"